In [13]:
import numpy as np
from ldpc.codes import ring_code
from ldpc.code_util import compute_code_distance
import ldpc.mod2 as mod2
from ldpc import protograph as pt
from ldpc.codes import hamming_code
from bposd.css import css_code
from bposd.hgp import hgp
from css_ss_decode_sim import css_ss_decode_sim
#from bposd.css_decode_sim import css_decode_sim

In [23]:
from lifted_hgp import *
H=pt.array([[(0,1)]])
qcode=lifted_hgp(lift_parameter=4,a=H, b=H)
qcode.test()

[[1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [1 0 0 1]]
[[1 1 0 0 1 0 0 1]
 [0 1 1 0 1 1 0 0]
 [0 0 1 1 0 1 1 0]
 [1 0 0 1 0 0 1 1]]
delta_0_2d.shape: (4, 8)
delta_m1_2d.shape: (8, 4)
[[1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
<class 'numpy.ndarray'>
[[1 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
<Unnamed CSS code>
 -Block dimensions: Pass
 -PCMs commute hz@hx.T==0: Pass
 -PCMs commute hx@hz.T==0: Pass
 -lx \in ker{hz} AND lz \in ker{hx}: Pass
 -lx and lz anticommute: Pass
 -<Unnamed CSS code> is a valid CSS code w/ params [8,2,nan]


True

In [29]:
print(qcode.mx_4d.shape)
print(qcode.hx_4d.shape)
print(qcode.hz_4d.shape)
print(qcode.mz_4d.shape)

(16, 64)
(64, 96)
(96, 64)
(64, 16)


In [27]:
hx=qcode.hz_proto.to_binary(lift_parameter=4)
hx

array([[1, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 1]])

In [10]:
from lifted_hgp_OG import *

In [11]:
qcode=lifted_hgp_OG(lift_parameter=4,a=H, b=H)


<Unnamed CSS code>
 -Block dimensions: Pass
 -PCMs commute hz@hx.T==0: Pass
 -PCMs commute hx@hz.T==0: Pass
 -lx \in ker{hz} AND lz \in ker{hx}: Pass
 -lx and lz anticommute: Pass
 -<Unnamed CSS code> is a valid CSS code w/ params [8,2,nan]


True

delta_0_2d.shape: (1, 2)
delta_m1_2d.shape: (2, 1)


TypeError: unsupported operand type(s) for %: 'RingOfCirculantsF2' and 'int'

In [ ]:
# dm1, d0 = build_2d_matrices(H)
# mz, hz, hx, mx = build_4d_matrices(dm1, d0)

# print("δ_{-2} * δ_{-1} ≡ 0 mod 2:", verify_delta_condition(hz, mz))
# print("δ_{-1} * δ_{0} ≡ 0 mod 2:", verify_delta_condition(hx, hz))
# print("δ_{0} * δ_{1} ≡ 0 mod 2:", verify_delta_condition(mx, hx))

# qcode=css_code(hx,hz.T)
# qcode.test()

In [19]:
        self.a=a

        self.a_m,self.a_n=self.a.shape

        if b is None:
            self.b=pt.copy(self.a)
        else:
            self.b=b
        
        self.b_m,self.b_n=self.b.shape

        self.hx1_proto=np.kron(self.a,I(self.b_n))
        self.hx2_proto=np.kron(I(self.a_m),self.b.T)
        self.hx_proto=pt.hstack([self.hx1_proto,self.hx2_proto])

        self.hz1_proto=np.kron(I(self.a_n),self.b)
        self.hz2_proto=np.kron(self.a.T,I(self.b_m))
        self.hz_proto=pt.hstack([self.hz1_proto,self.hz2_proto])

NameError: name 'a' is not defined

In [22]:
H=pt.array([
    [(0,1)]
])

In [20]:
a1=pt.array([
        [(0), (1)],
        [(6), (2)]])

In [18]:
a1=pt.array([
        [(0), (11), (7), (12)],
        [(1), (8), (1), (8)],
        [(11), (0), (4), (8)],
        [(6), (2), (4), (12)]])

In [71]:
hx=quantum_protograph_code.hx_proto.to_binary(lift_parameter=13)

In [73]:
qcode=css_code(hx,hz)

In [ ]:
qcode.test()

In [12]:
from bposd.css_decode_sim import css_decode_sim

a1=pt.array([
        [(0), (11), (7), (12)],
        [(1), (8), (1), (8)],
        [(11), (0), (4), (8)],
        [(6), (2), (4), (12)]])

qcode = lifted_hgp(lift_parameter=13,a=a1,b=a1)

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

In [ ]:


sim_input={
"error_rate": 0.10, #the physical error rate on the qubits
"target_runs": 1000, #the number of cycles to simulate
"bp_method": "minimum_sum", #the bp method
"ms_scaling_factor": 0.625, # the min-sum scaling factor
"osd_method": "osd_e", # OSD method
"osd_order": 10, #OSD order
"xyz_error_bias": [1,1,1], #the relative XYZ bias
"hadamard_rotate": True, #Hadamard rotate
"hadamard_rotate_sector1_length": qcode.hx1.shape[1], #the length of sector 1 qubit block. All qubits in sector 2 are Hadamard rotated
"channel_update": "x->z", # the channel update orientation
'max_iter': int(qcode.N/10), #the interation depth for BP
'tqdm_disable': False #show live stas
}
css_decode_sim(hx=qcode.hx,hz=qcode.hz,**sim_input)