In [10]:
import numpy as np
from ldpc.codes import ring_code
from ldpc.code_util import compute_code_distance
import ldpc.mod2 as mod2
from ldpc import protograph as pt
from ldpc.codes import hamming_code
from bposd.css import css_code
from bposd.hgp import hgp
from css_ss_decode_sim import css_ss_decode_sim
#from bposd.css_decode_sim import css_decode_sim

In [16]:
from lifted_hgp import *
H=pt.array([[(0,1)]])
qcode=lifted_hgp(lift_parameter=4,a=H, b=H)
qcode.test()

[[1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [1 0 0 1]]
[[1 1 0 0 1 0 0 1]
 [0 1 1 0 1 1 0 0]
 [0 0 1 1 0 1 1 0]
 [1 0 0 1 0 0 1 1]]
delta_0_2d.shape: (4, 8)
delta_m1_2d.shape: (8, 4)
<Unnamed CSS code>
 -Block dimensions: Pass
 -PCMs commute hz@hx.T==0: Pass
 -PCMs commute hx@hz.T==0: Pass
 -lx \in ker{hz} AND lz \in ker{hx}: Pass
 -lx and lz anticommute: Pass
 -<Unnamed CSS code> is a valid CSS code w/ params [8,2,nan]


True

In [19]:
qcode.hz_1_4d.shape

(32, 32)

In [ ]:
qcode.mx_4d

In [18]:
def verify_delta_condition(delta_i, delta_i_minus_1):
    """
    Verify that δ_i * δ_{i-1} = 0 mod 2.
    """
    product = np.mod(np.dot(delta_i, delta_i_minus_1), 2)  # Compute δ_i * δ_{i-1} mod 2
    return np.all(product == 0)  # Check if all entries are zero

print("δ_{-2} * δ_{-1} ≡ 0 mod 2:", verify_delta_condition(qcode.hz_4d, qcode.mz_4d))
print("δ_{-1} * δ_{0} ≡ 0 mod 2:", verify_delta_condition(qcode.hx_4d, qcode.hz_4d))
print("δ_{0} * δ_{1} ≡ 0 mod 2:", verify_delta_condition(qcode.mx_4d, qcode.hx_4d))

δ_{-2} * δ_{-1} ≡ 0 mod 2: True
δ_{-1} * δ_{0} ≡ 0 mod 2: True
δ_{0} * δ_{1} ≡ 0 mod 2: True


In [ ]:
qcode.

In [49]:
qcode.hx_4d.shape

(64, 96)

In [51]:
qcode.hz_4d.shape

(96, 64)

In [43]:
qcode.hx.shape

(4, 8)

In [41]:
qcode.hx1.shape

(4, 4)

In [23]:
sim_input={
    "error_rate": 0.10, #the physical error rate on the qubits
    "target_runs": 1000, #the number of cycles to simulate
    "bp_method": "minimum_sum", #the bp method
    "ms_scaling_factor": 0.625, # the min-sum scaling factor
    "osd_method": "osd_e", # OSD method
    "osd_order": 10, #OSD order
    "xyz_error_bias": [1,1,1], #the relative XYZ bias
    "hadamard_rotate": True, #Hadamard rotate
    "hadamard_rotate_sector1_length": qcode.hx1_2d.shape[1], #the length of sector 1 qubit block. All qubits in sector 2 are Hadamard rotated
    "channel_update": "x->z", # the channel update orientation
    'max_iter': int(qcode.N/10), #the interation depth for BP
    'tqdm_disable': False #show live stas
}

In [27]:
sim_input['hadamard_rotate_sector1_length']

4

In [8]:
css_decode_sim(hx=qcode.hx,hz=qcode.hz,**sim_input)

NameError: name 'qcode' is not defined